name: release

on:
  push:
    tags:
      - "ragstack-ai-langflow-base-*"

env:
  POETRY_VERSION: "1.8.2"

jobs:
  if_release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==$POETRY_VERSION
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Build project for distribution
        run: |
          make init
          make build_frontend
          make build_langflow_base
      - name: Check Version
        id: check-version
        run: |
          cd src/backend/base
          echo version=$(poetry version --short) >> $GITHUB_OUTPUT
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          cd src/backend/base
          poetry publish